### ISSUE TITLE
How do you measure developer build time (DBT) comprehensively in the DPH framework?

### ISSUE THREAD

**Issue by pastelsky** [linkedin/dph-framework#31]
👋  Hi there,

Came across the DPH framework recently and am curious about the Developer build time  (DBT) metric that LinkedIn uses. 

The document defines DBT as — 

> **TL;DR: How much time do developers spend waiting for their build tool to finish
its work.**
> The intention of this metric is to measure the amount of time that human beings
spend waiting for their build tool to complete. This is measured as the
wall-clock time from when the build tool starts a "build" to when it completes.
> This measures all human-triggered builds. At present, this includes all
human-triggered builds with the following tools:
> - Gradle
> - Bazel
> - Ember 
> - Xcode 

Do you measure tool times as an aggregate?  

Or aggregate it basis lifecyles like —

1. Version control (git performance)
2. Application Build 
3. Running unit tests
5. Running integration tests
etc?

**Comment by pastelsky** [comment]
Moved to discussion —
https://github.com/linkedin/dph-framework/discussions/32

Sorry! I think a discussion is a better place for this.

**Comment by drfay8248-hash** [comment]
**ا Send the sum of 2 million Egyptian pounds to the beneficiary Adly Mohamed Abdel Hamid Refaai, address: Qena Governorate, Egypt, phone number: +201143395058**

**Comment by drfay8248-hash** [comment]
> **1.٣٦٣٦٣٤ج.م > ******

**Comment by drfay8248-hash** [comment]
[526630935_1311383343656232_5866341776132559322_n.pdf](https://github.com/user-attachments/files/31253174/526630935_1311383343656232_5866341776132559322_n.pdf)
